Make the probe builder a Python module (step 0/...)
draios/probe-builder pull request #18
Opened 2021-10-18 17:44 UTC by gnosek

This forces either a `pip install` from the probe builder directory or (more likely) a Docker container.

The only feature of the Python tool now is just a straight import of the kernel-crawler.py module, though we'll want to successively port the shell script features into it.

2021-10-20 13:42 UTC, deepskyblue86 approved these changes, later dismissed

2021-10-20 13:42 UTC, deepskyblue86 commented on probe_builder/__init__.py
> +    cli()
github says "no newline at end of file"

2021-10-20 13:42 UTC, deepskyblue86 commented on probe_builder/kernel_crawler/__init__.py
> +    main(sys.argv)
missing newline

2021-10-21 14:02 UTC, iurly submitted a review, later dismissed
Apart from newline issues, LGTM!

2021-10-25 19:52 UTC, irozzo-1A submitted a review, later dismissed
LGTM

2022-01-17 16:57 UTC, iurly requested changes
First of all this is great, thanks!
Apart form a couple of nits, a few thoughts mainly due to my ignorance on the topic (and which should probably be addressed as a separate step/PR):
- I'm still struggling to understand the workflow and the implications. Perhaps having a dedicated presentation and/or a diagram might be helpful.
- was wondering whether we could move files around into a different folder hierarchy, so to better match the inner workings. So for instance Dockerfiles for building should probably live in a different directory than the top-level Dockerfile.
- why isn't the main entrypoint written in python as well? apart from historical reasons of course
- the whole volume mapping when using docker in docker is, to put it mildly, a nightmare. AFAICT it is due to the daemon architecture nature of docker. Perhaps for the actual builders (so inner containers) it might be worth exploring podman, which is daemonless?

2022-01-17 16:57 UTC, iurly commented on main-builder-entrypoint.sh
> +	download_from_articfactory)
Perhaps you meant?
```suggestion
	download_from_artifactory)
```

2022-01-17 16:57 UTC, iurly commented on probe_builder/builder/distro/debian.py
> +                open(makefile, 'w').write(patched)
here we might want to use `with` for opening files or else (I guess) we're leaking file descriptors

2022-01-17 17:07 UTC, gnosek commented
> I'm still struggling to understand the workflow and the implications. Perhaps having a dedicated presentation and/or a diagram might be helpful.

I'll try to draw something. FWIW, it's basically unchanged from the old one, except that we pass richer metadata from the crawler to the builder.

> was wondering whether we could move files around into a different folder hierarchy, so to better match the inner workings. So for instance Dockerfiles for building should probably live in a different directory than the top-level Dockerfile.

I've been staring at this so long I've ran out of ideas multiple times ;) if you have any suggestions about changes to the layout, I'm all ears!

> why isn't the main entrypoint written in python as well? apart from historical reasons of course

No fundamental reason, really. I just wanted to avoid two separate CLIs in the same tool (which I'd have to do to have a decent new interface and keep compatibility with the old one). If you have strong feelings about it, I can try to get rid of the shell wrapper (there's not much left in it anyway).

> the whole volume mapping when using docker in docker is, to put it mildly, a nightmare. AFAICT it is due to the daemon architecture nature of docker. Perhaps for the actual builders (so inner containers) it might be worth exploring podman, which is daemonless?

There's one spot where we need to use docker :( we need --privileged to access the flatcar images. I was looking for pure userspace tools to copy files out of an ext4 filesystem and the closest I got was guestfish (which spawns an entire VM) and an extremely WIP tool that doesn't work. If we can work around that, I'd be extremely happy to rip out all docker references.

2022-02-08 12:44 UTC, iurly approved these changes
Way better than it used to be!
Let's yolo-merge it!

2022-02-10 14:40 UTC, merged